from synthdocs.components.color import *
from synthdocs.components.component import Component
from synthdocs.components.corpus import *
from synthdocs.components.font import *
from synthdocs.components.image_effect import *
from synthdocs.components.layout import *
from synthdocs.components.text_effect import *
from synthdocs.components.texture import *
from synthdocs.components.transform import *
from synthdocs.components.wrapper import *
from synthdocs.components.artifact import *