quality: [50, 95]
short_size: [720, 1024]
aspect_ratio: [1, 2]

background:
  image:
    paths: [resources/background]
    weights: [1]

  effect:
    args:
      # gaussian blur
      - prob: 0
        args:
          sigma: [0, 10]
paper:
  image:
    paths: [resources/paper]
    weights: [1]
    alpha: [1, 1]
    grayscale: 1
    crop: 0.5

effect:
  args:
    # color
    - prob: 0.2
      args:
        rgb: [[0, 255], [0, 255], [0, 255]]
        alpha: [0, 0.2]
    # shadow
    - prob: 1
      args:
        intensity: [0, 160]
        amount: [0, 1]
        smoothing: [0.5, 1]
        bidirectional: 0
    # contrast
    - prob: 1
      args:
        alpha: [1, 1.5]
    # brightness
    - prob: 1
      args:
        beta: [-48, 0]
    # motion blur
    - prob: 0.5
      args:
        k: [3, 5]
        angle: [0, 360]
    # gaussian blur
    - prob: 1
      args:
        sigma: [0, 1.5]

ink_effect:
  args:
    # ink color swap
    - prob: 0.2
      args:
        ink_swap_color: "random"
        ink_swap_sequence_number_range: [5, 10]
        ink_swap_min_width_range: [2, 3]
        ink_swap_max_width_range: [100, 120]
        ink_swap_min_height_range: [2, 3]
        ink_swap_max_height_range: [100, 120]
        ink_swap_min_area_range: [10, 20]
        ink_swap_max_area_range: [400, 500]
    # lines degradation
    - prob: 0.2
      args:
        line_roi: [0.0, 0.0, 1.0, 1.0]
        line_gradient_range: [32, 255]
        line_gradient_direction: [0, 2]
        line_split_probability: [0.2, 0.4]
        line_replacement_value: [250, 255]
        line_min_length: [30, 40]
        line_long_to_short_ratio: [5, 7]
        line_replacement_probability: [0.8, 1.0]
        line_replacement_thickness: [3, 6]
    - prob: 0.2
      args:
        weights: [1, 1]
        args:        
          # dithering
          - dither: "random"
          # inkbleed
          - intensity_range: [0.5, 1.0]
            kernel_size:
              - [7, 7]
              - [5, 5]
              - [3, 3]
            severity: [0.4, 0.6]
    - prob: 0.2
      args:
        weights: [1, 1]
        args:        
          # ink shifter
          - text_shift_scale_range: [18, 27]
            text_shift_factor_range: [1, 4]
            text_fade_range: [0, 2]
            blur_kernel_size: [5, 5]
            blur_sigma: 0
            noise_type: "random"
          # bleedthrough
          - intensity_range: [0.1, 0.3]
            color_range: [32, 224]
            ksize: [17, 17]
            sigmaX: 1
            alpha: [0.1, 0.3]
            offsets: [10, 20]          
    - prob: 0.2
      args:
        weights: [1, 1]
        args:        
          # hollow
          - hollow_median_kernel_value_range: [71, 101]
            hollow_min_width_range: [1, 2]
            hollow_max_width_range: [150, 200]
            hollow_min_height_range: [1, 2]
            hollow_max_height_range: [150, 200]
            hollow_min_area_range: [10, 20]
            hollow_max_area_range: [2000, 5000]
            hollow_dilation_kernel_size_range: [1, 2]
          # letterpress
          - n_samples: [100, 2000]
            n_clusters: [200, 400]
            std_range: [500, 3000]
            value_range: [150, 224]
            value_threshold_range: [96, 128]
            blur: 1
    - prob: 0.2
      args:
        weights: [1, 1]
        args:        
          # low ink random lines
          - count_range: [100, 1000]
            use_consistent_lines: [True, False]
            noise_probability: 0.1
          # low ink periodic lines
          - count_range: [2, 5]
            period_range: [16, 32]
            use_consistent_lines: [True, False]
            noise_probability: 0.9

paper_effect:
  args:
    # color paper
    - prob: 0
      args:
        hue_range: [0, 255]
        saturation_range: [10, 40]
    - prob: 0.2
      args:
        weights: [1, 1, 1]
        args:
          # delaunay
          - n_points_range: [500, 800]
            n_horizontal_points_range: [500, 800]
            n_vertical_points_range: [500, 800]
            noise_type: "random"
            color_list: "default" # default, random
            color_list_alternate: "default" # default, random
          # pattern generator
          - imgx: [256, 512]
            imgy: [256, 512]
            n_rotation_range: [10, 15]
            color: "random"
            alpha_range: [0.25, 0.5]
          # voronoi
          - mult_range: [50, 80]
            seed: 19829813472
            num_cells_range: [500, 1000]
            noise_type: "random"
            background_value: [200, 255]
    # watermark
    - prob: 0.2
      args:
        watermark_word: "random"
        watermark_font_size: [10, 15]
        watermark_font_thickness: [20, 25]
        watermark_rotation: [0, 360]
        watermark_location: "random"
        watermark_color: "random"
        watermark_method: "darken"
    - prob: 0.2
      args:
        weights: [1, 1]
        args:
          # 첫 번째 Iterator 옵션: NoiseTexturize -> BrightnessTexturize
          - args:
              # NoiseTexturize 파라미터
              - sigma_range: [3, 10]
                turbulence_range: [2, 5]
                texture_width_range: [300, 500]
                texture_height_range: [300, 500]
              # BrightnessTexturize 파라미터
              - texturize_range: [0.9, 0.99]
                deviation: 0.03
          # 두 번째 Iterator 옵션: BrightnessTexturize -> NoiseTexturize
          - args:
              # BrightnessTexturize 파라미터
              - texturize_range: [0.9, 0.99]
                deviation: 0.03
              # NoiseTexturize 파라미터
              - sigma_range: [3, 10]
                turbulence_range: [2, 5]
                texture_width_range: [300, 500]
                texture_height_range: [300, 500]

post_effect:
  args:
    - prob: 0.1
      args:
        weights: [0, 1]
        args:
          # glitch effect
          - glitch_direction: "random"
            glitch_number_range: [8, 16]
            glitch_size_range: [5, 50]
            glitch_offset_range: [10, 50]
          # color shift
          - color_shift_offset_x_range: [3, 5]
            color_shift_offset_y_range: [3, 5]
            color_shift_iterations: [1, 2]
            color_shift_brightness_range: [0.9, 1.1]
            color_shift_gaussian_kernel_range: [1, 3]
    - prob: 0.1
      args:
        weights: [1, 1]
        args:
        # dirty drum
          - line_width_range: [1, 6]
            line_concentration: [0.05, 0.15]
            direction: [0,2]
            noise_intensity: [0.6, 0.95]
            noise_value: [64, 224]
            ksize: [[3, 3], [5, 5], [7, 7]]
            sigmaX: 0
        # dirty rollers
          - line_width_range: [2, 32]
            scanline_type: 0
    - prob: 0.1
      args:
        weights: [1, 1, 1]
        args:
        # lighting gradient
          - light_position:
            direction:
            max_brightness: 255
            min_brightness: 0
            mode: "gaussian"
            linear_decay_rate:
            transparency:
        # brightness
          - brightness_range: [0.5, 1.5]
            min_brightness: 0
            min_brightness_value: [120, 150]
        # gamma
          - gamma_range: [0.9, 1.1]
    - prob: 0.1
      args:
        weights: [1, 1]
        args:
        # subtlenoise
          - subtle_range: [100, 200]
        # jpeg
          - quality_range: [0, 95]
    - prob: 0.1
      args:
        weights: [1, 1]
        args:
          # markup
          - num_lines_range: [2, 7]
            markup_length_range: [0.5, 5]
            markup_thickness_range: [1, 10]
            markup_type: "random"
            markup_color: "random"
            single_word_mode: False
            repetitions: 10
          # scribbles
          - scribbles_type: "random"
            scribbles_location: "random"
            scribbles_size_range: [250, 600]
            scribbles_count_range: [1, 6]
            scribbles_thickness_range: [1, 3]
            scribbles_brightness_change: [32, 64, 128]
            scribbles_text: "random"
            scribbles_text_font: "random"
            scribbles_text_rotate_range: [0, 360]
            scribbles_lines_stroke_count_range: [1, 6]
    - prob: 0.1
      args:
        weights: [1, 1, 1]
        args:
          # bad photocopy
          - noise_mask: None
            noise_type: -1
            noise_side: "random"
            noise_iteration: [1, 2]
            noise_size: [1, 3]
            noise_value: [128, 196]
            noise_sparsity: [0.3, 0.6]
            noise_concentration: [0.1, 0.6]
            blur_noise: [True, False]
            blur_noise_kernel: [[3, 3], [5, 5], [7, 7]]
            wave_pattern: [True, False]
            edge_effect: [True, False]
          # shadow cast
          - shadow_side: "random"
            shadow_vertices_range: [1, 20]
            shadow_width_range: [0.3, 0.8]
            shadow_height_range: [0.3, 0.8]
            shadow_color: [0, 0, 0]
            shadow_opacity_range: [0.2, 0.9]
            shadow_iterations_range: [1, 2]
            shadow_blur_kernel_range: [101, 301]
          # low light noise
          - num_photons_range: [50, 100]
            alpha_range: [0.7, 1.0]
            beta_range: [10, 30]
            gamma_range: [1, 1.8]
            bias_range: [20, 40]
            dark_current_value: 1.0
            exposure_time: 0.2
            gain: 0.1
    - prob: 0.1
      args:
        weights: [1, 0]
        args:
          # noisy lines
          - noisy_lines_direction: "random"
            noisy_lines_location: "random"
            noisy_lines_number_range: [5, 20]
            noisy_lines_color: [0, 0, 0]
            noisy_lines_thickness_range: [1, 2]
            noisy_lines_random_noise_intensity_range: [0.01, 0.1]
            noisy_lines_length_interval_range: [0, 100]
            noisy_lines_gaussian_kernel_value_range: [3, 5]
            noisy_lines_overlay_method: "ink_to_paper"
          # bindings and fasteners
          - overlay_types: "darken"
            foreground: None
            effect_type: "random"
            width_range: "random"
            height_range: "random"
            angle_range: [-30, 30]
            ntimes: [2, 6]
            nscales: [0.9, 1.0]
            edge: "random"
            edge_offset: [10, 50]
            use_figshare_library: 0
    - prob: 0.1
      args:
        weights: [1, 1]
        args:
          # squish
          - squish_direction: "random"
            squish_location: "random"
            squish_number_range: [5, 10]
            squish_distance_range: [5, 7]
            squish_line: "random"
            squish_line_thickness_range: [1, 1]
          # geometric
          - scale: [0.75, 1.25]
            translation: [-10, 10]
            fliplr: [False]
            flipud: [False]
            crop:
            rotate_range: [-5, 5]
            randomize: 0
    - prob: 0.1
      args:
        weights: [1, 1]
        args:
          # dot matrix
          - dot_matrix_shape: "random"
            dot_matrix_dot_width_range: [3, 3]
            dot_matrix_dot_height_range: [3, 3]
            dot_matrix_min_width_range: [1, 2]
            dot_matrix_max_width_range: [150, 200]
            dot_matrix_min_height_range: [1, 2]
            dot_matrix_max_height_range: [150, 200]
            dot_matrix_min_area_range: [10, 20]
            dot_matrix_max_area_range: [2000, 5000]
            dot_matrix_median_kernel_value_range: [128, 255]
            dot_matrix_gaussian_kernel_value_range: [1, 3]
            dot_matrix_rotate_value_range: [0, 360]
          # faxify
          - scale_range: [0.3, 0.6]
            monochrome: [0, 1]
            monochrome_method: "random"
            monochrome_arguments: {}
            halftone: [0, 1]
            invert: 1
            half_kernel_size: [[1, 1], [2, 2]]
            angle: [0, 360]
            sigma: [1, 3]
    - prob: 0.1
      args:
        weights: [1, 1]
        args:
          # ink mottling
          - ink_mottling_alpha_range: [0.9, 0.9]
            ink_mottling_noise_scale_range: [2, 2]
            ink_mottling_gaussian_kernel_range: [3, 5]
          # # reflected light
          - reflected_light_smoothness: 0.8
            reflected_light_internal_radius_range: [0.0, 0.001]
            reflected_light_external_radius_range: [0.5, 0.8]
            reflected_light_minor_major_ratio_range: [0.9, 1.0]
            reflected_light_color: [255, 255, 255]
            reflected_light_internal_max_brightness_range: [0.75, 0.75]
            reflected_light_external_max_brightness_range: [0.5, 0.75]
            reflected_light_location: "random"
            reflected_light_ellipse_angle_range: [0, 360]
            reflected_light_gaussian_kernel_size_range: [5, 310]

business_registration:
  template_image:
    paths: resources/business_registration/background_image
  business_info:
    path: resources/business_registration/biz_info_cleaned.csv